# Generated by Django 4.1.2 on 2022-11-12 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_animal_domestico_animal_nome_animal_animal_preadador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='preadador',
            new_name='predador',
        ),
    ]
